GET http://localhost:5000/api/ HTTP/1.1

###

GET http://localhost:5000/api/inbox/undefined HTTP/1.1

###

PATCH http://localhost:5000/api/inbox/dai
Content-Type: application/json

{
    "removal": 240
}

###

DELETE http://localhost:5000/api/inbox/undefined